spring.application.name=AgendarReservas
server.port=8080

# Profile activo
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

app.jwt.access-token-expiration-ms=1800000
app.jwt.refresh-token-expiration-ms=604800000
app.jwt.issuer=AgendarReservas

app.cookie.secure=true
app.cookie.same-site=None
app.cookie.domain=

app.admin.create-on-startup=true
app.admin.username=admin
app.admin.email=admin@agendarreservas.com

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

# Spring AI - Google GenAI
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.5-flash
spring.ai.model.chat=google-genai

# Custom AI properties
app.ai.thinking-budget=10000
app.ai.system-prompt-path=classpath:prompts/agente_psicologo.txt

spring.ai.google.genai.chat.options.thinking-budget=${app.ai.thinking-budget}

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Propiedades de la app para email
app.mail.enabled=true
app.mail.from=${MAIL_FROM:noreply@agendarreservas.com}
app.mail.from-name=PsicoGestion Profesional

