# Perfil PRODUCCION - PostgreSQL Railway
spring.datasource.url=${PG_JDBC_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

app.cors.allowed-origins=${ALLOWED_ORIGINS}

# CSRF enabled in production
app.csrf.enabled=true

# JWT settings - Use environment variables in production
app.jwt.secret=${JWT_SECRET}

app.jwt.access-token-expiration-ms=1800000
app.jwt.refresh-token-expiration-ms=604800000