spring.application.name=AgendarReservas

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/p_agenda}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

