spring.application.name=AgendarReservas
server.port=${PORT:8080}

# Profile activo
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# JPA/Hibernate - SOLO POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS
app.cors.allowed-origins=${ALLOWED_ORIGINS}

